### ISSUE TITLE
ios_acls crashes when existing acl is empty

### ISSUE THREAD

**Issue by gejames** [ansible-collections/cisco.ios#189] opened 2020-10-27 14:13 UTC
##### SUMMARY
ios_acls crashes when existing acl is empty

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_acls

##### ANSIBLE VERSION

```
 ansible --version
ansible 2.9.14
  config file = /home/student1/.ansible.cfg
  configured module search path = ['/home/student1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student1/.ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student1/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student1/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student1/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/.ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/home/student1/.ansible.cfg) = 200
RETRY_FILES_ENABLED(/home/student1/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.2 (Ootpa)

##### STEPS TO REPRODUCE

When there is an empty acl 
```
!
ip access-list extended VTY-ACL
!
!
!
```

```
   - name: Make sure VTY ACL is correct
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
            # ip access-list extended VTY-ACL
            - name: VTY-ACL
              acl_type: extended
              aces:
              # permit tcp host {{ hostvars['ansible-1'].ansible_host }} any eq 22
              - grant: permit
                protocol: tcp
                source:
                  host: "{{ hostvars['ansible-1'].ansible_host }}"
                destination:
                  any: true
                  port_protocol:
                    eq: 22
```

##### EXPECTED RESULTS

changes should be made to acl as intended

##### ACTUAL RESULTS
```
TASK [Make sure VTY ACL is correct] ****************************************************************************************************************************************************
task path: /home/student1/configlet_vtyacl.yml:33
<3.237.254.241> ESTABLISH LOCAL CONNECTION FOR USER: student1
<3.237.254.241> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr `"&& mkdir "` echo /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219 `" && echo ansible-tmp-1603807845.9484065-67843-141502092549219="` echo /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219 `" ) && sleep 0'
Using module file /home/student1/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_acls.py
<3.237.254.241> PUT /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/tmp1r8tv5fz TO /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py
<3.237.254.241> EXEC /bin/sh -c 'chmod u+x /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/ /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py && sleep 0'
<3.237.254.241> EXEC /bin/sh -c '/usr/libexec/platform-python /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py && sleep 0'
<3.237.254.241> EXEC /bin/sh -c 'rm -f -r /home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py", line 102, in <module>
    _ansiballz_main()
  File "/home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in <module>
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1405, in main
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 86, in execute_module
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: deny any any
deny any any
      ^
% Invalid input detected at '^' marker.

rtr1(config-ext-nacl)#
fatal: [rtr1]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py", line 102, in <module>
        _ansiballz_main()
      File "/home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/student1/.ansible/tmp/ansible-local-67745n_e9mcdr/ansible-tmp-1603807845.9484065-67843-141502092549219/AnsiballZ_ios_acls.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in <module>
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1405, in main
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 86, in execute_module
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ida_y8p1/ansible_cisco.ios.ios_acls_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    ansible.module_utils.connection.ConnectionError: deny any any
    deny any any
          ^
    % Invalid input detected at '^' marker.

    rtr1(config-ext-nacl)#
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

```

**Comment by gejames** [comment] 2020-10-27 14:19
Moire output from a failed run.

```
 - name: Make sure VTY ACL is correct
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
            # ip access-list extended VTY-ACL
            - name: VTY-ACL
              acl_type: extended
              aces:
              # permit tcp host {{ hostvars['ansible-1'].ansible_host }} any eq 22
              - grant: permit
                protocol: tcp
                source:
                  host: "{{ hostvars['ansible-1'].ansible_host }}"
                destination:
                  any: true
                  port_protocol:
                    eq: 22
              # permit tcp 172.16.0.0 0.15.255.255 any eq 22
              - grant: permit
                protocol: tcp
                source:
                  address: 172.16.0.0
                  wildcard_bits: 0.15.255.255
                destination:
                  any: true
                  port_protocol:
                    eq: 22
              # permit tcp 192.168.0.0 0.0.255.255 any eq 22
              - grant: permit
                protocol: tcp
                source:
                  address: 192.168.0.0
                  wildcard_bits: 0.0.255.255
                destination:
                  any: true
                  port_protocol:
                    eq: 22
              # permit tcp 10.0.0.0 0.255.255.255 any eq 22 log-input
              - grant: permit
                protocol: tcp
                source:
                  address: 10.0.0.0
                  wildcard_bits: 0.255.255.255
                destination:
                  any: true
                  port_protocol:
                    eq: 22
              # deny   ip any any log-input
              - grant: deny
                log_input:
                protocol: ip
                source:
                  any: true
                destination:
                  any: true
        state: replaced
```


```
TASK [Make sure VTY ACL is correct] ****************************************************************************************************************************************************
task path: /home/student1/configlet_vtyacl.yml:33
<3.237.254.241> ESTABLISH LOCAL CONNECTION FOR USER: student1
<3.237.254.241> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/student1/.ansible/tmp/ansible-local-67954njhpr27o `"&& mkdir "` echo /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778 `" && echo ansible-tmp-1603808169.367694-68054-72831925035778="` echo /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778 `" ) && sleep 0'
Using module file /home/student1/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_acls.py
<3.237.254.241> PUT /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/tmp02dqzzud TO /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py
<3.237.254.241> EXEC /bin/sh -c 'chmod u+x /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/ /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py && sleep 0'
<3.237.254.241> EXEC /bin/sh -c '/usr/libexec/platform-python /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py && sleep 0'
<3.237.254.241> EXEC /bin/sh -c 'rm -f -r /home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py", line 102, in <module>
    _ansiballz_main()
  File "/home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in <module>
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1405, in main
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 93, in execute_module
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 58, in get_acl_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 114, in get_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 69, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 600, in render_config
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 220, in populate_port_protocol
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 220, in populate_port_protocol
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 220, in populate_port_protocol
  [Previous line repeated 982 more times]
  File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 140, in populate_port_protocol
RecursionError: maximum recursion depth exceeded in comparison
fatal: [rtr1]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py", line 102, in <module>
        _ansiballz_main()
      File "/home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/student1/.ansible/tmp/ansible-local-67954njhpr27o/ansible-tmp-1603808169.367694-68054-72831925035778/AnsiballZ_ios_acls.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in <module>
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1405, in main
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 93, in execute_module
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 58, in get_acl_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 114, in get_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 69, in populate_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 600, in render_config
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 220, in populate_port_protocol
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 220, in populate_port_protocol
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 220, in populate_port_protocol
      [Previous line repeated 982 more times]
      File "/tmp/ansible_cisco.ios.ios_acls_payload_etgsshsy/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 140, in populate_port_protocol
    RecursionError: maximum recursion depth exceeded in comparison
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by justjais** [comment] 2021-01-06 10:46
@gejames PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:50
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:50 UTC
