### ISSUE TITLE
ios_l2_interfaces bug when more than 14 trunk vlans

### ISSUE THREAD

**Issue by inigoleaga** [ansible-collections/cisco.ios#303] opened 2021-04-20 14:41 UTC
##### SUMMARY
When you configure an interface with more than 14 vlans, the task using ios_L2_interfaces always adds the 15th, 16th and so on... even if they are already configured.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- cisco.ios.ios_l2_interfaces

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/com/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

- Cisco Switch OS version: 15.2(2)E9

##### STEPS TO REPRODUCE

Run a task with more than 14 vlans as "allowed_vlans". In this case, I'm configuring this interface with 15 vlans:

```cisco.ios
interface Port-channel1
 description ENLACE A CORE PO22
 switchport trunk allowed vlan 11,21,31,40,42-46,48,49,66,121,252,253,828,921
 switchport trunk allowed vlan add 924
 switchport mode trunk
 ip dhcp snooping trust
end
```

The task:
```yaml
    - name: Ensure all Access VLANs are allowed in access uplinks
      cisco.ios.ios_l2_interfaces:
        config:
        - name: Port-channel1
          mode: trunk
          trunk:
            allowed_vlans: 11,21,31,40,42-46,48,49,66,121,252,253,828,921,924
```

##### EXPECTED RESULTS

As I already have the that vlans allowed, I expect to recieve an "OK", not a "CHANGED"

##### ACTUAL RESULTS

The task adds the 15th vlan, but it is already configured.

```paste below
    ],
    "changed": true,
    "commands": [
        "interface Port-channel1",
        "switchport trunk allowed vlan add 924"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "access": null,
                    "mode": "trunk",
                    "name": "Port-channel1",
                    "trunk": {
                        "allowed_vlans": [
                            "11",
                            "21",
                            "31",
                            "40",
                            "42",
                            "43",
                            "44",
                            "45",
                            "46",
                            "48",
                            "49",
                            "66",
                            "121",
                            "252",
                            "253",
                            "828",
                            "921",
                            "924"
                        ],
                        "encapsulation": null,
                        "native_vlan": null,
                        "pruning_vlans": null
                    },
                    "voice": null
                }
            ],
            "running_config": null,
            "state": "merged"
        }

```

**Comment by JoanieAda** [comment] 2021-04-29 17:53
Just wanted to add that the issue seem to be caused by the facts gathered as the additional Vlans is clearly not listed
```
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "before": [
        {
            "name": "Port-channel1",
            "trunk": {
                "allowed_vlans": [
                    "11",
                    "21",
                    "31",
                    "40",
                    "42-46",
                    "48",
                    "49",
                    "66",
                    "121",
                    "252",
                    "253",
                    "828",
                    "921"
                ]
            }
        },
```
Digging through deeper my guess would be the issue actually stem from the following module
`cisco.ios.plugins.module_utils.network.ios.facts.l2_interfaces`

Essentially any vlans that are listed as part of additional `switchport trunk allowed vlan add` commands in configuration aren't gathered in facts therefore are considered as non existent and added as part of the new config.

For example in the following configuration, vlans 253,828,830 and 850 would not show up in the gathered facts
```
interface Port-channel1
 switchport trunk allowed vlan 11,21,31,40,42-46,48,49,66,101,103,106,121,252
 switchport trunk allowed vlan add 253,828,830,850
```

**Comment by justjais** [comment] 2021-05-09 17:49
@inigoleaga this issue is a duplicate of the issue raised under #77, also I've raised the PR to fix the respective issue, and if feasible kindly verify the fix and confirm if it works as expected.
Closing this issue, plz ref #77 for discussion around the respective bug.

**Closed by justjais** 2021-05-09 17:49 UTC
