### ISSUE TITLE
Command timeout triggered

### ISSUE THREAD

**Issue by nafstad** [ansible-collections/cisco.ios#369] opened 2021-07-07 19:07 UTC
##### SUMMARY

Running a simple show version to  ISE, this keep timing out.
But now and then it is able to get through , and I get get the result.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/stian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stian/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/stian/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/stian/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.general 3.0.2 
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Cisco Identity Services Engine
---------------------------------------------
Version      : 3.0.0.458

##### STEPS TO REPRODUCE

```yaml
---
- name: Show config test
  hosts: ise
  connection: local
  gather_facts: false 

  tasks:
     
    - name: Show version
      ios_command:
        commands: show version
      
      register: command_output

    - debug:
        var: command_output.stdout
```

##### EXPECTED RESULTS

This from the ISE:
ISE-LAB-Test/admin# show version

Cisco Application Deployment Engine OS Release: 3.0
ADE-OS Build Version: 3.0.8.091
ADE-OS System Architecture: x86_64

Copyright (c) 2005-2020 by Cisco Systems, Inc.
All rights reserved.
Hostname: ISE-LAB-Test

Version information of installed applications
---------------------------------------------

Cisco Identity Services Engine
---------------------------------------------
Version      : 3.0.0.458
Build Date   : Sat Aug 29 22:51:28 2020
Install Date : Sun Jul  4 21:36:24 2021

##### ACTUAL RESULTS

```paste below
ansible-playbook ver2.yml -vvvv
ansible-playbook [core 2.11.1] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/stian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stian/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/stian/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/stian/.local/bin/ansible-playbook
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
redirecting (type: modules) ansible.builtin.ios_command to cisco.ios.ios_command
Loading collection cisco.ios from /home/stian/.ansible/collections/ansible_collections/cisco/ios
Loading callback plugin default of type stdout, v2.0 from /home/stian/.local/lib/python3.8/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: ver2.yml *******************************************************************************************************************************************************************************************************************
Positional arguments: ver2.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
forks: 5
1 plays in ver2.yml

PLAY [Show config test] **************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Show version] ******************************************************************************************************************************************************************************************************************
task path: /etc/ansible/ver2.yml:9
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
Loading collection ansible.netcommon from /home/stian/.ansible/collections/ansible_collections/ansible/netcommon
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
<10.203.15.38> attempting to start connection
<10.203.15.38> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /home/stian/.local/bin/ansible-connection
<10.203.15.38> local domain socket does not exist, starting it
<10.203.15.38> control socket path is /home/stian/.ansible/pc/b0290b0a19
<10.203.15.38> redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
<10.203.15.38> Loading collection ansible.netcommon from /home/stian/.ansible/collections/ansible_collections/ansible/netcommon
<10.203.15.38> redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
<10.203.15.38> Loading collection cisco.ios from /home/stian/.ansible/collections/ansible_collections/cisco/ios
<10.203.15.38> redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
<10.203.15.38> local domain socket listeners started successfully
<10.203.15.38> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /home/stian/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os ios
<10.203.15.38> 
<10.203.15.38> local domain socket path is /home/stian/.ansible/pc/b0290b0a19
redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
<10.203.15.38> Using network group action ios for ios_command
redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
<10.203.15.38> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<10.203.15.38> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<10.203.15.38> ESTABLISH LOCAL CONNECTION FOR USER: stian
<10.203.15.38> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06 `"&& mkdir "` echo /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/ansible-tmp-1625684791.303384-1141796-108510698261516 `" && echo ansible-tmp-1625684791.303384-1141796-108510698261516="` echo /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/ansible-tmp-1625684791.303384-1141796-108510698261516 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.ios_command to cisco.ios.ios_command
Using module file /home/stian/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_command.py
<10.203.15.38> PUT /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/tmp61pcodxz TO /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/ansible-tmp-1625684791.303384-1141796-108510698261516/AnsiballZ_ios_command.py
<10.203.15.38> EXEC /bin/sh -c 'chmod u+x /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/ansible-tmp-1625684791.303384-1141796-108510698261516/ /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/ansible-tmp-1625684791.303384-1141796-108510698261516/AnsiballZ_ios_command.py && sleep 0'
<10.203.15.38> EXEC /bin/sh -c '/usr/bin/python3 /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/ansible-tmp-1625684791.303384-1141796-108510698261516/AnsiballZ_ios_command.py && sleep 0'
<10.203.15.38> EXEC /bin/sh -c 'rm -f -r /home/stian/.ansible/tmp/ansible-local-1141791cveb7_06/ansible-tmp-1625684791.303384-1141796-108510698261516/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_ios_command_payload_bqezylf5/ansible_ios_command_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 94, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_ios_command_payload_bqezylf5/ansible_ios_command_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [10.203.15.38]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show version"
            ],
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "command timeout triggered, timeout value is 60 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
10.203.15.38               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by KB-perByte** [comment] 2021-07-08 11:56
Hi @nafstad,
As you mentioned that you get the output of the playbook in some executions.
The times when the play time-outs, can you confirm that you had not encountered the prompt
`Enter session number to resume or press <Enter> to start a new one:`
The prompt might stop the execution of the command on the target device.

**Comment by nafstad** [comment] 2021-07-20 19:58
Hello @KB-perByte,

I can confirm that I have not encountered that.

I tried several times now, to an ISE 2.7 and ISE 3.0.

Was after a few min able to get it through:

From hosts:

`[ise]
10.203.15.38

[ise:vars]
ansible_network_os=ios
ansible_connection=network_cli
`

Playbook:


`---

 - hosts: ise
   gather_facts: no
   tasks:
     - name: Show Version
       cisco.ios.ios_command:
         commands: show version
       register: command_output

     - name: PRINT TO TERMINAL WINDOW
       debug:
         msg: "{{command_output.stdout}}"`

Output:(Tried to run it right after to see if it still gave me the same output)
`stian@ubuntu-ansible:~/ansible$ ansible-playbook show_version_ios3.yml 

PLAY [ise] ************************************************************************************************************************************************************************************************************************************************************************************

TASK [Show Version] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [10.203.15.38]

TASK [PRINT TO TERMINAL WINDOW] ***************************************************************************************************************************************************************************************************************************************************************
ok: [10.203.15.38] => {
    "msg": [
        "Cisco Application Deployment Engine OS Release: 3.0\nADE-OS Build Version: 3.0.8.091\nADE-OS System Architecture: x86_64\n\nCopyright (c) 2005-2020 by Cisco Systems, Inc.\nAll rights reserved.\nHostname: ISE-LAB-Test\n\n\nVersion information of installed applications\n---------------------------------------------\n\nCisco Identity Services Engine\n---------------------------------------------\nVersion      : 3.0.0.458\nBuild Date   : Sat Aug 29 22:51:28 2020\nInstall Date : Sun Jul  4 21:36:24 2021"
    ]
}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************************
10.203.15.38               : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

stian@ubuntu-ansible:~/ansible$ ansible-playbook show_version_ios3.yml 

PLAY [ise] ************************************************************************************************************************************************************************************************************************************************************************************

TASK [Show Version] ***************************************************************************************************************************************************************************************************************************************************************************
fatal: [10.203.15.38]: FAILED! => {"changed": false, "msg": "command timeout triggered, timeout value is 60 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************************
10.203.15.38               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 `

**Comment by KB-perByte** [comment] 2021-08-02 12:16
hi @nafstad,
The issue is about the target device asks for which session to connect back on re-establishment of the connection,
you can try handling that via adding `terminal_initial_prompt` ref - [ansible.netcommon.network_cli ](https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/network_cli_connection.html#parameter-terminal_initial_prompt) to handle the session prompt encountered on login prompt.

**Comment by KB-perByte** [comment] 2021-09-23 13:51
Hey @nafstad,
Closing this issue, as the IOS collection won't adopt changes to handle operation on Cisco ISE devices.
You can still try the `terminal_initial_prompt` or supplying a command that terminates the session in the ISE device from the playbook itself.
Thank you!

**Closed** 2021-09-23 13:51 UTC
Labels: needs_info
