### ISSUE TITLE
ios_vlans failing for vlan facts on IOS 16.9.5 

### ISSUE THREAD

**Issue by benjdudas** [ansible-collections/cisco.ios#63] opened 2020-05-29 14:49 UTC
##### SUMMARY

This ios_vlans task is being tested against ios 15.2(2)E7 and 16.9.5. Switches running 15.2(2)E7 are successful but fails with the following traceback for devices running 16.9.5.

```
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-local-3zRW5fX/ansible-tmp-1590277408.56-174-101926446002067/AnsiballZ_ios_vlans.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-local-3zRW5fX/ansible-tmp-1590277408.56-174-101926446002067/AnsiballZ_ios_vlans.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-local-3zRW5fX/ansible-tmp-1590277408.56-174-101926446002067/AnsiballZ_ios_vlans.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 733, in <module>
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 728, in main
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 70, in execute_module
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 52, in get_vlans_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 106, in get_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 77, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_xZACnX/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 127, in render_config
IndexError: list index out of range
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_vlans
./module_utils/network/ios/facts/vlans/vlans.py
##### ANSIBLE VERSION

```paste below
[root@xxx-ansible03]# ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
[root@xxx-ansible03]# ansible-config dump --only-changed
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /etc/ansible/ansible.log
```

##### OS / ENVIRONMENT

```
<hostname>#show version
Cisco IOS XE Software, Version 16.09.05
Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.9.5, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Thu 30-Jan-20 18:17 by mcpre

ROM: IOS-XE ROMMON
BOOTLDR: CAT3K_CAA Boot Loader (CAT3K_CAA-HBOOT-M) Version 4.66, RELEASE SOFTWARE (P)

Technology Package License Information: 

------------------------------------------------------------------------------
Technology-package                                     Technology-package
Current                        Type                       Next reboot  
------------------------------------------------------------------------------
ipbasek9                Smart License                    ipbasek9            
None                    Subscription Smart License       None                          


Smart Licensing Status: UNREGISTERED/EVAL MODE

cisco WS-C3650-48PD (MIPS) processor (revision A0) with 832395K/6147K bytes of memory.
Processor board ID FDO1811Q040
1 Virtual Ethernet interface
50 Gigabit Ethernet interfaces
2 Ten Gigabit Ethernet interfaces
2048K bytes of non-volatile configuration memory.
4194304K bytes of physical memory.
250456K bytes of Crash Files at crashinfo:.
1609272K bytes of Flash at flash:.
0K bytes of WebUI ODM Files at webui:.

Base Ethernet MAC Address          : 64:12:25:15:b7:80
Motherboard Assembly Number        : 73-15125-05
Motherboard Serial Number          : FDO18101N27
Model Revision Number              : A0
Motherboard Revision Number        : A0
Model Number                       : WS-C3650-48PD
System Serial Number               : FDO1811Q040


Switch Ports Model              SW Version        SW Image              Mode   
------ ----- -----              ----------        ----------            ----   
*    1 52    WS-C3650-48PD      16.9.5            CAT3K_CAA-UNIVERSALK9 INSTALL


Configuration register is 0x102    


Configuration register is 0xF

```

##### STEPS TO REPRODUCE

**task:**
```yaml
- cisco.ios.ios_vlans:
     state: overridden
     config:
       '{{ abc_campus_vlans }}'
  when: ansible_network_os == 'ios'
```
**vars_file:**
```yaml
abc_campus_vlans:
 - name: default
   shutdown: disabled
   state: active
   vlan_id: 1
 - name: ABC
   shutdown: disabled
   state: active
   vlan_id: 4
```
**show vlan:**
```
<hostname>#show vlan

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    
4    ABC                             active    
5    ABCDE-X.X.X.X_23           active    Gi1/0/1, Gi1/0/2, Gi1/0/3, Gi1/0/4, Gi1/0/5, Gi1/0/6, Gi1/0/7, Gi1/0/8, Gi1/0/9, Gi1/0/10, Gi1/0/11, Gi1/0/12, Gi1/0/13, Gi1/0/14, Gi1/0/15, Gi1/0/16, Gi1/0/17, Gi1/0/18, Gi1/0/19, Gi1/0/20, Gi1/0/21
                                                Gi1/0/22, Gi1/0/23, Gi1/0/24, Gi1/0/25, Gi1/0/26, Gi1/0/27, Gi1/0/28, Gi1/0/29, Gi1/0/30, Gi1/0/31, Gi1/0/32, Gi1/0/33, Gi1/0/34, Gi1/0/35, Gi1/0/36, Gi1/0/37, Gi1/0/38, Gi1/0/39, Gi1/0/40, Gi1/0/41, Gi1/0/42
                                                Gi1/0/43, Gi1/0/44, Gi1/0/45, Gi1/0/46, Gi1/0/47, Gi1/0/48
42   AB-CD—VLANNAME_X.X.X.0_24 active    
51   ABC_VLAN_X.X.X.X_24        active    
55   ABCDEF-GUEST-VLAN-X.X.X.0_24  active    
56   ABC-DEF-AAAAAAAAA-X.X.X.0_24 active    
57   ABCDE-WLAN-X.X.X.0_24         active    
58   TEST-ABCDEFGH-NETWORK            active    
60   AB-X.X.X.0_22                  active    
87   VLAN-VLANNAME-X.X.X.0_24   active    
98   ABCDEFG                         active    
99   ABC-HR-X.X.X.0_27              active    
100  ABCDE_X.X.X.X_27              active    
101  PRINTERS_X.X.X.0_25           active    
103  AB-CONSOLES_X.X.X.0_23        active    
105  IT_X.X.X.0_24                 active    
106  ABC_X.X.X.0_23                active    
107  ABC-FINANCE_X.X.X.0_25        active    
109  ADMIN_X.X.X.0_25               active    
110  ABC-DEF-X.X.X.128_25           active    
112  CONFROOMS_X.X.X.0_23         active    
113  ABC_X.X.X.0_24                active    
114  ABCDCOM-X.X.X.0_24            active    
115  ABCDEFGH-CAM_X.X.X.0_24      active    
116  ABC-VLANNAME-X.X.X.0_28     active    
119  ABCDEF-MASKSTATION-X.X.X.0_28
                                      active    
120  ABC-EFG-VLANNAME-X.X.X.0_27  active    
121  ABC-WLAN-THUNDERVLAN-X.X.X.X_24
                                      active    
122  VLAN-WLAN-X.X.34.0_23       active    
123  AB-WLAN-X.X.X.0_23            active    
124  MASKVLAN-WLAN-X.X.X.0_28    active    
125  VLANX-WLAN-X.X.X.0_28       active    
126  ABC-DEFG-X.X.X.0_23           active    
127  CAMPUS-DEFAULT-X.X.X.0_22     active    
130  ABCDEFG-X.X.X.0_28           active    
138  ABC-X.X.X.0_24                active    
139  GUEST-ABC-X.X.X.0_26          active    
141  AB-CDEFGH-NETWORK_X.X.X.0_28   active    
450  AB-CDEFG-NETWORK                 active    
998  ABC-JUMPBOX-X.X.X.0_24       active    
999  ABC-MGMT-X.X.X.0_22          active    
1002 fddi-default                     act/unsup 
1003 trcrf-default                    act/unsup 
1004 fddinet-default                  act/unsup 
1005 trbrf-default                    act/unsup 

VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
1    enet  100001     1500  -      -      -        -    -        0      0   
4    enet  100004     1500  -      -      -        -    -        0      0   
5    enet  100005     1500  -      -      -        -    -        0      0   
42   enet  100042     1500  -      -      -        -    -        0      0   
51   enet  100051     1500  -      -      -        -    -        0      0   
55   enet  100055     1500  -      -      -        -    -        0      0   
56   enet  100056     1500  -      -      -        -    -        0      0   
57   enet  100057     1500  -      -      -        -    -        0      0   
58   enet  100058     1500  -      -      -        -    -        0      0   
60   enet  100060     1500  -      -      -        -    -        0      0   
87   enet  100087     1500  -      -      -        -    -        0      0   
98   enet  100098     1500  -      -      -        -    -        0      0   
99   enet  100099     1500  -      -      -        -    -        0      0   
100  enet  100100     1500  -      -      -        -    -        0      0   
101  enet  100101     1500  -      -      -        -    -        0      0   
103  enet  100103     1500  -      -      -        -    -        0      0   
105  enet  100105     1500  -      -      -        -    -        0      0   
106  enet  100106     1500  -      -      -        -    -        0      0   
107  enet  100107     1500  -      -      -        -    -        0      0   
109  enet  100109     1500  -      -      -        -    -        0      0   
110  enet  100110     1500  -      -      -        -    -        0      0   
112  enet  100112     1500  -      -      -        -    -        0      0   
113  enet  100113     1500  -      -      -        -    -        0      0   
114  enet  100114     1500  -      -      -        -    -        0      0   
115  enet  100115     1500  -      -      -        -    -        0      0   
116  enet  100116     1500  -      -      -        -    -        0      0   
119  enet  100119     1500  -      -      -        -    -        0      0   
120  enet  100120     1500  -      -      -        -    -        0      0   
121  enet  100121     1500  -      -      -        -    -        0      0   
          
VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
122  enet  100122     1500  -      -      -        -    -        0      0   
123  enet  100123     1500  -      -      -        -    -        0      0   
124  enet  100124     1500  -      -      -        -    -        0      0   
125  enet  100125     1500  -      -      -        -    -        0      0   
126  enet  100126     1500  -      -      -        -    -        0      0   
127  enet  100127     1500  -      -      -        -    -        0      0   
130  enet  100130     1500  -      -      -        -    -        0      0   
138  enet  100138     1500  -      -      -        -    -        0      0   
139  enet  100139     1500  -      -      -        -    -        0      0   
141  enet  100141     1500  -      -      -        -    -        0      0   
450  enet  100450     1500  -      -      -        -    -        0      0   
998  enet  100998     1500  -      -      -        -    -        0      0   
999  enet  100999     1500  -      -      -        -    -        0      0   
1002 fddi  101002     1500  -      -      -        -    -        0      0   
1003 trcrf 101003     4472  1005   3276   -        -    srb      0      0   
1004 fdnet 101004     1500  -      -      -        ieee -        0      0   
1005 trbrf 101005     4472  -      -      15       ibm  -        0      0   


VLAN AREHops STEHops Backup CRF
---- ------- ------- ----------
1003 7       7       off

Remote SPAN VLANs
------------------------------------------------------------------------------


Primary Secondary Type              Ports
------- --------- ----------------- ------------------------------------------
```

**show vtp status:**
```
<hostname>#show vtp status
VTP Version capable             : 1 to 3
VTP version running             : 3
VTP Domain Name                 : rkv-vtp-domain
VTP Pruning Mode                : Disabled
VTP Traps Generation            : Disabled
Device ID                       : c4c6.039b.cf80

Feature VLAN:
--------------
VTP Operating Mode                : Transparent
Number of existing VLANs          : 46
Number of existing extended VLANs : 0
Maximum VLANs supported locally   : 4096


Feature MST:
--------------
VTP Operating Mode                : Transparent


Feature UNKNOWN:
--------------
VTP Operating Mode                : Transparent

```

##### ACTUAL RESULTS
Trying to mask all customer information here so if you would like to see the full job log, playbook, and switch information just reach out internally.

**Comment by justjais** [comment] 2020-05-31 12:12
@benjdudas Though I am not able to reproduce the error from my end with the scenario mentioned in the issue comment.
I have made a slight modification from the code end to handle the logic in a more robust way. PR raised: https://github.com/ansible-collections/cisco.ios/pull/64, can you please verify if the customer is able to resolve the error with the PR fix and they are not having any other issues coz of PR. Thanks

**Comment by saifelyzal** [comment] 2020-07-02 17:44
The customer still seen issue.

"changed": false, 
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-local-3mZn6Sz/ansible-tmp-1593394002.01-174-257395059992713/Ansi
ballZ_ios_vlans.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-local-3mZn6Sz/ansible-tmp-1593394002.01-174-25739505
9992713/AnsiballZ_ios_vlans.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-local-3mZn6Sz/ansible-tmp-1593394002.01-174-257395059992713/AnsiballZ_ios_vlans.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 176, in run_module\\n    fname, loader, pkg_name)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 82, in _run_module_code\\n    mod_name, mod_fname, mod_loader, pkg_name)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 72, in _run_code\\n    exec code in run_globals\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\\", line 748, in <module>\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\\", line 743, in main\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\\", line 70, in execute_module\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\\", line 52, in get_vlans_facts\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\\", line 110, in get_facts\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\\", line 128, in get_network_resources_facts\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\\", line 77, in populate_facts\\n  File \\"/tmp/ansible_cisco.ios.ios_vlans_payload_1vNRSl/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\\", line 125, in render_config\\nValueError: invalid literal for int() with base 10: 'active'\\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", 
    "rc": 1

**Comment by justjais** [comment] 2020-07-07 12:13
@saifelyzal there's some issue with `show vlan` output facts parsing and if we have the support case with a complete output of customer's `show vlan` it'd greatly help in resolving the issue as currently, with the traceback you've shared it seems that `vlan status` is parsed wrongly instead of `vlan id` which is resulting into the traceback error and this is not happening when I am trying from my end with the same `vlans` configured as mentioned under issue description.

**Comment by matejv** [comment] 2020-10-17 10:40
Seeing the same issue. (using cisco.ios collection version 1.1.0)

Problem occurs when a VLAN name is so long that `show vlan` output is split across two lines. See vlan 888 here:

```
lbravos-tsp#show vlan

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Te1/3, Te1/4, Te1/5, Te1/6, Te1/7, Te1/8, Te1/9, Te1/10, Te1/11, Te1/12
                                                Te1/13, Te1/14, Te1/15
2    braavos_pedagosko                active    
3    braavos_admin                    active    
4    braavos_dmz                      active    
797  lanso                            active    
888  a_very_long_vlan_name_a_very_long_vlan_name
                                      active    
1002 fddi-default                     act/unsup 
1003 trcrf-default                    act/unsup 
1004 fddinet-default                  act/unsup 
1005 trbrf-default                    act/unsup 

VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
1    enet  100001     1500  -      -      -        -    -        0      0   
2    enet  100002     1500  -      -      -        -    -        0      0   
3    enet  100003     1500  -      -      -        -    -        0      0   
4    enet  100004     1500  -      -      -        -    -        0      0   
5    enet  100005     1500  -      -      -        -    -        0      0   
          
VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
6    enet  100006     1500  -      -      -        -    -        0      0   
7    enet  100007     1500  -      -      -        -    -        0      0   
8    enet  100008     1500  -      -      -        -    -        0      0   
12   enet  100012     1500  -      -      -        -    -        0      0   
13   enet  100013     1500  -      -      -        -    -        0      0   
14   enet  100014     1500  -      -      -        -    -        0      0   
166  enet  100166     1500  -      -      -        -    -        0      0   
797  enet  100797     1500  -      -      -        -    -        0      0   
888  enet  100888     1500  -      -      -        -    -        0      0   
1002 fddi  101002     1500  -      -      -        -    -        0      0   
1003 trcrf 101003     4472  1005   3276   -        -    srb      0      0   
1004 fdnet 101004     1500  -      -      -        ieee -        0      0   
1005 trbrf 101005     4472  -      -      15       ibm  -        0      0   


VLAN AREHops STEHops Backup CRF
---- ------- ------- ----------
1003 7       7       off

Remote SPAN VLANs
------------------------------------------------------------------------------


Primary Secondary Type              Ports
------- --------- ----------------- ------------------------------------------

lbravos-tsp#
```

**Comment by justjais** [comment] 2020-10-21 08:41
@matejv fix for the same is merged to IOS collection and is queued for IOS this month's release.

**Closed by justjais** 2020-10-21 08:41 UTC
Labels: needs_info
