### ISSUE TITLE
ios_facts and gather_network_resources: acls fails with `list index out of range`

### ISSUE THREAD

**Issue by lotaris-xx** [ansible-collections/cisco.ios#159] opened 2020-09-24 17:10 UTC
##### SUMMARY
When running the ios_facts module to gather acl resources, the module fails with `list index out of range`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_facts

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible_priv/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 16.09.04
Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.9.4, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2019 by Cisco Systems, Inc.
Compiled Thu 22-Aug-19 17:33 by mcpre
Model Number                       : WS-C3850-48P

##### STEPS TO REPRODUCE

```
- hosts: lab
  gather_facts: false
  tasks:
  - cisco.ios.ios_facts:
      gather_subset: all
      gather_network_resources: acls
```
Here are the extended acls configured on the device:
```
 ip access-list extended ACL_WEBAUTH_REDIRECT
 deny   ip any host 10.212.23.22
 permit tcp any any eq www
 permit tcp any any eq 443
 permit tcp any any eq 8443
 deny   ip any host 10.211.87.192
 deny   udp any any eq domain
 deny   udp any eq bootpc any eq bootps
ip access-list extended CAP1-FILTER-LIST
 permit ip any any
```

##### EXPECTED RESULTS

Would expect to the module to return with acl resource facts.

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible_priv/user/.ansible/tmp/ansible-local-3618679omw2dux4/ansible-tmp-1600966737.7078514-3618709-87954408524365/AnsiballZ_ios_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible_priv/user/.ansible/tmp/ansible-local-3618679omw2dux4/ansible-tmp-1600966737.7078514-3618709-87954408524365/AnsiballZ_ios_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible_priv/user/.ansible/tmp/ansible-local-3618679omw2dux4/ansible-tmp-1600966737.7078514-3618709-87954408524365/AnsiballZ_ios_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_facts_payload_g2lqs8ub/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 236, in <module>
  File "/tmp/ansible_cisco.ios.ios_facts_payload_g2lqs8ub/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 229, in main
  File "/tmp/ansible_cisco.ios.ios_facts_payload_g2lqs8ub/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 110, in get_facts
  File "/tmp/ansible_cisco.ios.ios_facts_payload_g2lqs8ub/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_facts_payload_g2lqs8ub/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 69, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_facts_payload_g2lqs8ub/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 600, in render_config
  File "/tmp/ansible_cisco.ios.ios_facts_payload_g2lqs8ub/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 208, in populate_port_protocol
IndexError: list index out of range
```

**Comment by ybonde87** [comment] 2020-12-07 13:19
I'm also getting the exactly same error while working with the ios_acls module. Not sure what I've missed in the script.

Below is my script to push a standard ACL onto a Cisco 9300 switch.

---

- name: test acl
  hosts: CS01
  gather_facts: false
  tasks:

   - name: Configure Permit ACL 45 on Cisco Switch 
     cisco.ios.ios_acls:
       config:
       - afi: ipv4
         acls:
         - name: 45
           acl_type: standard
           aces:
           - grant: permit
             source:
               address: 172.23.83.65
           - grant: permit
             source:
               address: 10.0.0.0
               wildcard_bits: 0.0.0.255
       state: merged

**Comment by justjais** [comment] 2021-01-06 10:47
@lotaris-xx PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:50
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:50 UTC
