### ISSUE TITLE
cisco.ios.ios_acls reports The error was: IndexError: list index out of range

### ISSUE THREAD

**Issue by apellini** [ansible-collections/cisco.ios#203] opened 2020-11-07 17:25 UTC
##### SUMMARY

Using this module with state replaced it goes in traceback with The error was: IndexError: list index out of range

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_acls

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /root/hardening/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/root/hardening/ansible.cfg) = 10
DEFAULT_GATHERING(/root/hardening/ansible.cfg) = no
DEFAULT_HOST_LIST(/root/hardening/ansible.cfg) = ['/root/hardening/inventory']
DEFAULT_LOG_PATH(/root/hardening/ansible.cfg) = /root/hardening/ansible.log
DEFAULT_ROLES_PATH(/root/hardening/ansible.cfg) = ['/root/hardening/roles']
DEPRECATION_WARNINGS(/root/hardening/ansible.cfg) = False
HOST_KEY_CHECKING(/root/hardening/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Rhel 7

##### STEPS TO REPRODUCE

```yaml
- name: Check ACL for ACL 96
  cisco.ios.ios_acls:
    config:
      - afi: ipv4
        acls:
          - name: 96
            aces:
              - grant: permit
                source:
                  address: 10.6.0.0
                  wildcard_bits: 0.0.15.255
              - grant: permit
                source:
                  address: 192.168.164.0
                  wildcard_bits: 0.0.0.255
              - grant: permit
                source:
                  address: 10.19.125.0
                  wildcard_bits: 0.0.0.255
    state: replaced
```

##### EXPECTED RESULTS

I expected an idempotent result that describes what is changed on that ACL.

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
failed: [papa] (item={'device': 'papa', 'flash': ['flash0:'], 'IP': '1.1.1.1', 'version': '15.2(4.0.55)E', 'model': 'IOSv', 'cmdb_interface': 'Vlan102', 'aaa_group': ['PIPPO'], 'server_group': [' server-private 1.1.1.1 timeout 3 key 7 dasdsad', ' server-private 2.2.2.2 timeout 3 key 7 sadsadasd']}) => {"ansible_loop_var": "item", "changed": false, "item": {"IP": "1.1.1.1", "aaa_group": ["PIPPO"], "cmdb_interface": "Vlan102", "device": "papa", "flash": ["flash0:"], "model": "IOSv", "server_group": [" server-private 2.2.2.2 timeout 3 key 7 asdasdas", " server-private 1.1.1.1 timeout 3 key 7 dasdaad"], "version": "15.2(4.0.55)E"}, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-3658nrqej5f7/ansible-tmp-1604769200.1988034-3933-34032573965201/AnsiballZ_ios_acls.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-3658nrqej5f7/ansible-tmp-1604769200.1988034-3933-34032573965201/AnsiballZ_ios_acls.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-3658nrqej5f7/ansible-tmp-1604769200.1988034-3933-34032573965201/AnsiballZ_ios_acls.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1410, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1405, in main\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 77, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 58, in get_acl_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 118, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 69, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 600, in render_config\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_W5yNxg/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 208, in populate_port_protocol\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
failed: [bravo] (item={'device': 'bravo', 'flash': ['flash0:'], 'IP': '2.2.2.2', 'version': '15.2(4.0.55)E', 'model': 'IOSv', 'cmdb_interface': 'Vlan102', 'aaa_group': ['PIPPO'], 'server_group': [' server-private 1.1.1.1 timeout 3 key 7 dasda', ' server-private 2.2.2.2 timeout 3 key 7 dasd']}) => {"ansible_loop_var": "item", "changed": false, "item": {"IP": "2.2.2.2", "aaa_group": ["PIPPO"], "cmdb_interface": "Vlan102", "device": "bravo", "flash": ["flash0:"], "model": "IOSv", "server_group": [" server-private 2.2.2.2 timeout 3 key 7 dasdas", " server-private 1.1.1.1 timeout 3 key 7 sdasdsaddsa"], "version": "15.2(4.0.55)E"}, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-3658nrqej5f7/ansible-tmp-1604769200.2733378-3934-14108856866672/AnsiballZ_ios_acls.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-3658nrqej5f7/ansible-tmp-1604769200.2733378-3934-14108856866672/AnsiballZ_ios_acls.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-3658nrqej5f7/ansible-tmp-1604769200.2733378-3934-14108856866672/AnsiballZ_ios_acls.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1410, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1405, in main\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 77, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 58, in get_acl_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 118, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 69, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 600, in render_config\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_OXhA35/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 208, in populate_port_protocol\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by justjais** [comment] 2021-01-06 10:44
@apellini PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:49
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:49 UTC
