### ISSUE TITLE
ios_facts: Error while gathering info about acls

### ISSUE THREAD

**Issue by misch42** [ansible-collections/cisco.ios#201] opened 2020-11-06 17:44 UTC
##### SUMMARY
I want to gather info about the ios_facts on my 2960. But I run into an error: list index out of range

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_facts

##### ANSIBLE VERSION
```
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/napalm_ansible']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/napalm_ansible']
```

##### OS / ENVIRONMENT
```
CentOS Linux release 8.2.2004 (Core)
```

ansible and ansible-galaxy collections installed with pip.

##### STEPS TO REPRODUCE

```yaml
---
- name: Test
  hosts: switch07
  gather_facts: False
  vars:
    ansible_network_os: cisco.ios.ios
  
  tasks:
  - name: Test
    cisco.ios.ios_facts:
      gather_subset: all
      gather_network_resources:
        - 'acls'
```

##### EXPECTED RESULTS

List ACL facts on device.

##### ACTUAL RESULTS

Error.

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/misch/.ansible/tmp/ansible-local-9855xvo7zow7/ansible-tmp-1604684392.3748226-9876-259288997060240/AnsiballZ_ios_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/misch/.ansible/tmp/ansible-local-9855xvo7zow7/ansible-tmp-1604684392.3748226-9876-259288997060240/AnsiballZ_ios_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/misch/.ansible/tmp/ansible-local-9855xvo7zow7/ansible-tmp-1604684392.3748226-9876-259288997060240/AnsiballZ_ios_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 236, in <module>                                                                                                                                                                        
  File "/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 229, in main                                                                                                                                                                            
  File "/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 118, in get_facts                                                                                                                                                    
  File "/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 128, in get_network_resources_facts                                                                                                                       
  File "/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 69, in populate_facts                                                                                                                                            
  File "/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 600, in render_config                                                                                                                                            
  File "/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 208, in populate_port_protocol                                                                                                                                   
IndexError: list index out of range
[DEPRECATION WARNING]: Distribution centos 8.2.2004 on host switch07 should use /usr/libexec/platform-python, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [switch07]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/misch/.ansible/tmp/ansible-local-9855xvo7zow7/ansible-tmp-1604684392.3748226-9876-259288997060240/AnsiballZ_ios_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/misch/.ansible/tmp/ansible-local-9855xvo7zow7/ansible-tmp-1604684392.3748226-9876-259288997060240/AnsiballZ_ios_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/misch/.ansible/tmp/ansible-local-9855xvo7zow7/ansible-tmp-1604684392.3748226-9876-259288997060240/AnsiballZ_ios_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py\", line 236, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py\", line 229, in main\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 118, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 128, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 69, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 600, in render_config\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_xo4ul_d3/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 208, in populate_port_protocol\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by justjais** [comment] 2021-01-06 10:44
@misch42 PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:49
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:49 UTC
