### ISSUE TITLE
Issue with ios_facts Querying Extended ACLs with Wildcard Masks

### ISSUE THREAD

**Issue by imareporter** [ansible-collections/cisco.ios#188] opened 2020-10-27 13:28 UTC
##### SUMMARY

When querying extended ACLs from a Cisco device running IOS 15.6(2), `re` appears to error out during the `.findall()` function if the rule has a wildcard mask:

~~~
Extended IP access list test
    10 permit udp 192.168.10.0 0.0.0.255 host 10.0.10.1
~~~

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
root@tester1:/home# ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
---
- name: Fetch ACLs
  hosts: Cisco
  gather_facts: false
  collections:
    - cisco.ios

  tasks:
    - name: Fetch ACLs
      ios_facts:
        gather_network_resources: acls
```

##### EXPECTED RESULTS

`ios_facts` should be able to parse the wildcard mask properly.

##### ACTUAL RESULTS

```paste below
Using module file /root/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_facts.py
<192.168.3.1> PUT /root/.ansible/tmp/ansible-local-51205T7kL/tmplKvVRq TO /root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/AnsiballZ_ios_facts.py
<192.168.3.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/ /root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/AnsiballZ_ios_facts.py && sleep 0'
<192.168.3.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/AnsiballZ_ios_facts.py && sleep 0'
<192.168.3.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/AnsiballZ_ios_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/AnsiballZ_ios_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-51205T7kL/ansible-tmp-1603744327.92-587-274922593261635/AnsiballZ_ios_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_ios_facts_payload_VKKE5s/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 236, in <module>
  File "/tmp/ansible_ios_facts_payload_VKKE5s/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 229, in main
  File "/tmp/ansible_ios_facts_payload_VKKE5s/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 114, in get_facts
  File "/tmp/ansible_ios_facts_payload_VKKE5s/ansible_ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_ios_facts_payload_VKKE5s/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 69, in populate_facts
  File "/tmp/ansible_ios_facts_payload_VKKE5s/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 591, in render_config
  File "/tmp/ansible_ios_facts_payload_VKKE5s/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 239, in populate_source_destination
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

**Comment by imareporter** [comment] 2020-12-03 18:09
@justjais @rohitthakur2590 Just following up on the issue and seeing if there are any updates.

**Comment by imareporter** [comment] 2020-12-04 13:23
https://github.com/ansible-collections/cisco.ios/pull/211

**Comment by justjais** [comment] 2021-01-06 10:46
@imareporter PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:50
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:50 UTC
