### ISSUE TITLE
cisco.ios.ios_acls not working on vios_l2 images

### ISSUE THREAD

**Issue by JulioPDX** [ansible-collections/cisco.ios#221] opened 2020-12-28 21:00 UTC
##### SUMMARY

Using the ios_acls module to delete all existing ACLs on devices. This works when using the router images. When trying to delete all ACLs using a switch image, the task fails.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

```yaml
- name: delete all ACLs
  cisco.ios.ios_acls:
    state: deleted
  ignore_errors: yes
```

##### ANSIBLE VERSION

```
ansible 2.10.4
  config file = /home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg
  configured module search path = ['/home/juliopdx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/juliopdx/git/auto_venv/lib/python3.8/site-packages/ansible
  executable location = /home/juliopdx/git/auto_venv/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = True
DEFAULT_FORKS(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = ['/home/juliopdx/git/ccnp_enarsi_lab_manual/hosts']
DEFAULT_STDOUT_CALLBACK(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = False
HOST_KEY_CHECKING(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/juliopdx/git/ccnp_enarsi_lab_manual/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Ansible running on Ubuntu 20.04, Ansible version posted above.

Using the following CML image for switches

```
Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Version 15.2(CML_NIGHTLY_20190423)FLO_DSGS7, EARLY DEPLOYMENT DEVELOPMENT BUILD, synced to  V152_6_0_81_E
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2019 by Cisco Systems, Inc.
Compiled Tue 23-Apr-19 04:48 by mmen
```

##### STEPS TO REPRODUCE

1. Install ansible 2.10.4
2.  Install dependencies
3.  Install collection
4.  run playbook to delete all ACLs on switch image

```yaml
- name:  Playbook to delete ACLs
  hosts: swichezs
  gather_facts: False
  strategy: free
  tasks:
    - name: delete all ACLs
      cisco.ios.ios_acls:
        state: deleted
      ignore_errors: yes
```

##### EXPECTED RESULTS

I expect an ok message if no ACLs exist or changed if there is an ACL to remove. 

##### ACTUAL RESULTS

```
TASK [destroy_lab : delete all ACLs] **************************************************************************************************************************
task path: /home/juliopdx/git/ccnp_enarsi_lab_manual/roles/destroy_lab/tasks/reset_acl_prefix.yaml:2
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in <module>
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1405, in main
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 77, in execute_module
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 57, in get_acl_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 113, in get_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 69, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 600, in render_config
  File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 208, in populate_port_protocol
IndexError: list index out of range
fatal: [A1]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in <module>
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1405, in main
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 77, in execute_module
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 57, in get_acl_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 113, in get_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 69, in populate_facts
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 600, in render_config
      File "/tmp/ansible_cisco.ios.ios_acls_payload_ccc13akd/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py", line 208, in populate_port_protocol
    IndexError: list index out of range
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
...ignoring
```

**Comment by justjais** [comment] 2021-01-06 10:33
@JulioPDX PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by JulioPDX** [comment] 2021-01-06 18:01
@justjais Thank you for letting me know. Excited to keep on exploring the collection!

**Comment by justjais** [comment] 2021-01-11 11:49
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:49 UTC
