### ISSUE TITLE
Getting TypeError: 'NoneType' object is not iterable from ios_acl_interfaces module witj state deleted

### ISSUE THREAD

**Issue by ugarix** [ansible-collections/cisco.ios#278] opened 2021-03-18 18:58 UTC
##### SUMMARY

My playbook is as follows, I simply want to remove all ACLs from interfaces as per the documentation example:
---
- name: configure/audit VTY ACL
  hosts: ios1
  gather_facts: no
  collections:
  - cisco.ios
  tasks:
  - name: remove ACLs from interfaces
    ios_acl_interfaces:
      config:
      state: deleted

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_acl_interfaces module with cisco.ios collection latest developer release (cisco.ios:==2.0.1-dev5)
##### ANSIBLE VERSION

```paste below
(env) [vagrant@server1 ansible]$ ansible --versionansible 2.10.6
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/env/lib/python3.8/site-packages/ansible
  executable location = /home/vagrant/env/bin/ansible
  python version = 3.8.7 (default, Feb 19 2021, 15:35:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/vagrant/ansible/ansible.cfg) = ['/home/vagrant/ansible/hosts
DEFAULT_STDOUT_CALLBACK(/home/vagrant/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/vagrant/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/vagrant/ansible/ansible.cfg) = /home/vagrant/env/bin/python
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/vagrant/ansible/ansible.cfg) = 500
```

##### OS / ENVIRONMENT

controller centos 7.x, target OS: Cisco IOS XE Software, Version 16.06.04

##### STEPS TO REPRODUCE

Run this playbook:
---
- name: configure/audit VTY ACL 
  hosts: ios1
  gather_facts: no
  collections:
  - cisco.ios
  tasks:
  - name: remove ACLs from interfaces
    ios_acl_interfaces:
      config:
      state: deleted

```yaml
---
- name: configure/audit VTY ACL 
  hosts: ios1
  gather_facts: no
  collections:
  - cisco.ios
  tasks:
  - name: remove ACLs from interfaces
    ios_acl_interfaces:
      config:
      state: deleted
```

##### EXPECTED RESULTS

I expect the ACLs to be removed from interfaces.

##### ACTUAL RESULTS

(env) [vagrant@server1 ansible]$ ansible-playbook acl_interfaces.yml -vvv
ansible-playbook 2.10.6
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/env/lib/python3.8/site-packages/ansible
  executable location = /home/vagrant/env/bin/ansible-playbook
  python version = 3.8.7 (default, Feb 19 2021, 15:35:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /home/vagrant/ansible/ansible.cfg as config file
host_list declined parsing /home/vagrant/ansible/hosts as it did not pass its verify_file() method
script declined parsing /home/vagrant/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /home/vagrant/ansible/hosts as it did not pass its verify_file() method
Parsed /home/vagrant/ansible/hosts inventory source with ini plugin
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: acl_interfaces.yml *******************************************************
1 plays in acl_interfaces.yml

PLAY [configure/audit VTY ACL] *****************************************************
META: ran handlers
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios

TASK [remove ACLs from interfaces] *************************************************
task path: /home/vagrant/ansible/acl_interfaces.yml:8
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios
<10.10.4.2> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<10.10.4.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1 `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499 `" && echo ansible-tmp-1616088204.3246279-3773-114190006854499="` echo /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499 `" ) && sleep 0'
Using module file /home/vagrant/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py
<10.10.4.2> PUT /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/tmpwi7v4plq TO /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py
<10.10.4.2> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/ /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py && sleep 0'
<10.10.4.2> EXEC /bin/sh -c '/home/vagrant/env/bin/python3.8 /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py && sleep 0'
<10.10.4.2> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acl_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 598, in <module>
  File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 593, in main
  File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 76, in execute_module
  File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 126, in set_config
  File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 153, in set_state
  File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 253, in _state_deleted
  File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 396, in _clear_config
TypeError: 'NoneType' object is not iterable
fatal: [ios1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py", line 102, in <module>
        _ansiballz_main()
      File "/home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/vagrant/.ansible/tmp/ansible-local-3768s8829mb1/ansible-tmp-1616088204.3246279-3773-114190006854499/AnsiballZ_ios_acl_interfaces.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acl_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 598, in <module>
      File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 593, in main
      File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 76, in execute_module
      File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 126, in set_config
      File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 153, in set_state
      File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 253, in _state_deleted
      File "/tmp/ansible_ios_acl_interfaces_payload_av40xnxm/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 396, in _clear_config
    TypeError: 'NoneType' object is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *************************************************************************
ios1                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(env) [vagrant@server1 ansible]$ 

```paste below

```

**Comment by njohnsn** [comment] 2021-03-18 21:09
There is a bug that is fixed in the latest beta release see issue #274
I was able to install the developer release with the command 
```
ansible-galaxy collection install cisco.ios:==2.0.1-dev5 --pre --force
```

**Comment by ugarix** [comment] 2021-03-19 08:34
I already tested with the developer release you mentioned. I'm having this issue with ios_acl_interfaces module, not ios_acls module. I think the bug fix in the latest dev release is for ios_acls module.

**Comment by justjais** [comment] 2021-03-19 10:47
@ugarix Thanks for logging the issue, but with bug details I am unable to reproduce the error but as the traceback seems relevant, can you plz share the config output for the cmd: `sh running-config | include interface|ip access-group|ipv6 traffic-filter` for triaging the issue further.

**Comment by Kela5** [comment] 2021-04-30 11:26
do you have a timeline of adding the bugfix to the main branch of the ios collection?

**Comment by justjais** [comment] 2021-04-30 11:31
@Kela5 as shared in an earlier comment I wasn't able to reproduce the issue on the box I test with, so if you're facing a similar issue can you share the respective config of `acl_interfaces` with which you're facing the issue

**Comment by Kela5** [comment] 2021-04-30 12:33
cisco.ios.ios_acls  was affected with the config below:

  tasks:
    - name: Use the ACLs resource module to gather the current config
      cisco.ios.ios_acls:
        config:
        state: gathered
      register: acls
      tags: acls_collect

**Comment by justjais** [comment] 2021-05-01 10:44
@Kela5 it seems you're trying to refer some different issue as this particular issue is tagged for `ios_acl_interfaces` module, but you've referred `ios_acls` module in your gathered example.

**Comment by KB-perByte** [comment] 2021-06-01 08:45
@Kela5 Closing as the issue is inactive

**Closed by KB-perByte** 2021-06-01 08:45 UTC
Labels: needs_info
