### ISSUE TITLE
ios_bgp: is not taking the masklen value to configure the advertised networks

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/cisco.ios#952] opened 2023-10-23 02:43 UTC
### Summary

network mask is not applied on the router

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

ubuntu 

### Steps to Reproduce

```yaml (paste below)
    - name: configure the bgp
      cisco.ios.ios_bgp:
        config:
          bgp_as: "{{ protocols.bgp.bgp_as }}"
          router_id: "{{ protocols.bgp.router_id }}"
          log_neighbor_changes: true
          neighbors: "{{ protocols.bgp.neighbors }}"
          networks: "{{ protocols.bgp.networks }}"

protocols:
  bgp:
    bgp_as: 65501
    router_id: 10.10.10.111
    log_neighbor_changes: true
    neighbors:
      - neighbor: 10.10.10.112
        remote_as: 65501
        update_source: Loopback0
    networks:
      - prefix: 10.101.1.0
        masklen: 24
      - prefix: 10.101.2.0
        masklen: 24

```

### Expected Results

router bgp 65501
 bgp router-id 10.10.10.111
 bgp log-neighbor-changes
 network 10.101.1.0  mask 255.255.255.0
 network 10.101.2.0 mask 255.255.255.0
 neighbor 10.10.10.112 remote-as 65501
 neighbor 10.10.10.112 update-source Loopback0

### Actual Results

```console
router bgp 65501
 bgp router-id 10.10.10.111
 bgp log-neighbor-changes
 network 10.101.1.0
 network 10.101.2.0
 neighbor 10.10.10.112 remote-as 65501
 neighbor 10.10.10.112 update-source Loopback0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Akasurde** [comment] 2023-10-23 02:43
cc @devopsnetworks

**Comment by KB-perByte** [comment] 2023-11-02 05:57
Hey @Akasurde and @devopsnetworks, The ios_bgp module is deprecated and is expected to be gone in the November 2023 release.
Please consider using the bgp_global and bgp_address_famility modules. 

Closing the issue as the issue is reported for a deprecated module.
Regards,

**Closed by KB-perByte** 2023-11-02 05:57 UTC
