### ISSUE TITLE
ios_static_routes and ios_facts fails with 'index out of range'

### ISSUE THREAD

**Issue by robindan** [ansible-collections/cisco.ios#367] opened 2021-07-02 09:41 UTC
##### SUMMARY
When trying to fetch the static routes from a device or when trying to add a new static route on a device that has around 460 static route entries, we always get a *list index out of range* error.

```
    - name: Gather existing routes
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources:
          - static_routes
      register: reg_ios_config
```

Or

```
    - name: Add the requested route
      cisco.ios.ios_static_routes:
        state: merged
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: "{{ ip_prefix }}"
                    next_hops:
                      - forward_router_address: "{{ next_hop }}"
```

Both work fine when using the legacy code (gather_subset config) or legacy module (ios_static_route).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_static_routes
ios_facts with gather_network_resources

##### ANSIBLE VERSION

```
ansible 2.10.6
  config file = /mnt/c/Users/user/Documents/Gitlab/ansible-icon/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/share/virtualenvs/ansible-icon-aZqOzgTG/lib/python3.8/site-packages/ansible
  executable location = /home/user/.local/share/virtualenvs/ansible-icon-aZqOzgTG/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### COLLECTION VERSION

```
# /home/user/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  2.3.0  
```

##### EXPECTED RESULTS
Routes to be fetched or added

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_cisco.ios.ios_facts_payload_cfuhu04x/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 133, in get_network_resources_facts
    inst.populate_facts(
  File "/tmp/ansible_cisco.ios.ios_facts_payload_cfuhu04x/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 75, in populate_facts
    obj = self.render_config(
  File "/tmp/ansible_cisco.ios.ios_facts_payload_cfuhu04x/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 224, in render_config
    if is_valid_ip(route[2]):
fatal: [192.0.2.26]: FAILED! => changed=false 
  invocation:
    module_args:
      available_network_resources: false
      gather_network_resources:
      - static_routes
      gather_subset:
      - min
      provider: null
  msg: list index out of range
```

**Comment by KB-perByte** [comment] 2021-07-16 03:51
Hi @WintyBe,
Unable to reproduce the issue at our end, the facts gathered while using the newer resource module post the merged play specified do not give out the above error. Can you help us with the verbose output of the merged play and your configuration, to check if there is some data that the module is unable to parse! 
Thank you!

**Comment by WintyBe** [comment] 2021-07-16 08:11
This is all the debug shows (on -vvvv):
`The full traceback is:
  File "/tmp/ansible_cisco.ios.ios_facts_payload_w_rbqvnv/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 133, in get_network_resources_facts
    inst.populate_facts(
  File "/tmp/ansible_cisco.ios.ios_facts_payload_w_rbqvnv/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 75, in populate_facts
    obj = self.render_config(
  File "/tmp/ansible_cisco.ios.ios_facts_payload_w_rbqvnv/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 224, in render_config
    if is_valid_ip(route[2]):
fatal: [10.250.5.24]: FAILED! => changed=false 
  invocation:
    module_args:
      available_network_resources: false
      gather_network_resources:
      - static_routes
      gather_subset:
      - min
      provider: null
  msg: list index out of range
`

I could paste all our routes, but then I would have to obscure them a bit as they are our company's announced public routes. But to summarize, we have several 'forms' of static routes. The most obvious with just a next-hop (being an IP or Null0):
`ip route 192.168.24.0 255.255.255.248 192.168.12.26`
Some with the permanent keyword:
`ip route 10.0.0.0 255.0.0.0 Null0 permanent`
One special case with a track, a next-hop and an interface
`ip route 192.168.66.5 255.255.255.255 TenGigabitEthernet0/1/0 192.168.66.5 track 10`
The Mgmt VRF route:
`ip route vrf mgmt 0.0.0.0 0.0.0.0 192.0.2.2`
And finally some IPv6 stuff, but I'm not sure if the module handles those (they're not important in my example anyway):
`ipv6 route 2001:DB8::/32 2001:DB8:3000:1`

I tried again with the permanent, special, IPv6 and 350 regular routes removed but the result is the same (list index out of range).

**Comment by KB-perByte** [comment] 2021-07-24 09:23
Hi @WintyBe,
on basis of the commands you shared, I see `ipv6 route 2001:DB8::/32 2001:DB8:3000:1` this being in the configuration is supposed to be an incomplete command. And removing/completing that from the config should make the facts work! 
Can you please confirm!

**Comment by WintyBe** [comment] 2021-08-18 08:39
Sorry for the late response.

Why would it be incomplete config? It's a simple IPv6 route. 
I already tried with all the IPv6 routes removed and the result remains the same.

**Comment by NetworkingB2A** [comment] 2021-12-01 06:44
I am also having this same issue. I also seem to have the issue when a null0  static route is in the config

**Comment by craigers521** [comment] 2021-12-06 22:47
bump. same, also with Null0 route.

**Closed** 2021-12-18 10:26 UTC
Labels: needs_info, static_routes
