### ISSUE TITLE
l2_interfaces not correctly identifying all trunks as a trunk

### ISSUE THREAD

**Issue by venturawpg** [ansible-collections/cisco.ios#70] opened 2020-06-05 20:20 UTC
##### SUMMARY

l2_interfaces, which is part of ios_facts gathering, is not correctly identifying all trunk ports as trunks.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /home/mark6847/git/ansible-is-networks/config-compliance-checks/ansible.cfg
  configured module search path = ['/home/mark6847/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mark6847/virtual-environments/ansible-python3/lib/python3.7/site-packages/ansible
  executable location = /home/mark6847/virtual-environments/ansible-python3/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/home/userxxxx/git/ansible-is-networks/config-compliance-checks/ansible.cfg) = False
INTERPRETER_PYTHON(/home/userxxxx/git/ansible-is-networks/config-compliance-checks/ansible.cfg) = /usr/bin/python
```

##### OS / ENVIRONMENT

Cisco Catalyst 3850 switch
WS-C3850-48U
IOS 16.6.7

##### STEPS TO REPRODUCE

I notice this issue whenever there is a trunk interface that allows ALL vlans and no native vlan is defined on it. When that is the case, then ios_facts does not identify it as a trunk as it should. This is a completely valid configuration to have on a trunk.

**Example Cisco config that doesn't get identified as a trunk**
interface GigabitEthernet1/0/48
 switchport mode trunk
 switchport nonegotiate
 ip dhcp snooping trust

**What Ansible ios_facts l2_interfaces sees**
{
    "name": "GigabitEthernet1/0/48"
},

For comparison of what does work, if the trunk port has an allowed vlan list, a native vlan, or both defined then it works as expected.

**Example Cisco config that works**
 interface GigabitEthernet1/0/48
 switchport trunk native vlan 999
 switchport trunk allowed vlan 2726,2727
 switchport mode trunk
 switchport nonegotiate
 ip dhcp snooping trust

**What Ansible ios_facts l2_interfaces sees**
{
    "name": "GigabitEthernet1/0/48",
    "trunk": {
	"allowed_vlans": [
	    "2726",
	    "2727"
	],
	"native_vlan": 999
    }
},

```yaml

```

##### EXPECTED RESULTS

I expect ios_facts l2_interfaces to identify all trunks as trunks regardless of if a native vlan or allowed list is defined on the trunk.

##### ACTUAL RESULTS

As shown above in the steps to reproduce, the trunk is not identified as being a trunk when the native vlan or allowed list is not defined on it.

```paste below

```

**Comment by justjais** [comment] 2020-07-07 08:36
@venturawpg Thanks for raising the issue, and this issue seems to be duplicate of issue another broader issue reported under #77, thus closing this issue.
Feel free to reopen the issue if you feel it's not a similar issue.

**Closed by justjais** 2020-07-07 08:36 UTC
