### ISSUE TITLE
Index out of range when gathering ACLs

### ISSUE THREAD

**Issue by craigbruenderman** [ansible-collections/cisco.ios#166] opened 2020-10-02 14:25 UTC
##### SUMMARY
Index out of range when trying to use any of the acl modules

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_acls:

```
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /usr/local/bin/python3

ansible 2.10.1
  config file = None
  configured module search path = ['/Users/craigb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/craigb/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ansible
  executable location = /Users/craigb/.pyenv/versions/3.8.5/bin/ansible
  python version = 3.8.5 (default, Sep 26 2020, 16:18:24) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### STEPS TO REPRODUCE

```yaml
    - name: Gather listed acls with provided configurations
      cisco.ios.ios_acls:
        config:
        state: gathered

```

##### ACTUAL RESULTS

```
TASK [Gather listed acls with provided configurations] ***************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [10.202.3.220]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/craigb/.ansible/tmp/ansible-local-49086tzdz2tu6/ansible-tmp-1601648670.938601-49146-53314854473876/AnsiballZ_ios_acls.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/craigb/.ansible/tmp/ansible-local-49086tzdz2tu6/ansible-tmp-1601648670.938601-49146-53314854473876/AnsiballZ_ios_acls.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/craigb/.ansible/tmp/ansible-local-49086tzdz2tu6/ansible-tmp-1601648670.938601-49146-53314854473876/AnsiballZ_ios_acls.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1410, in <module>\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1405, in main\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 93, in execute_module\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 57, in get_acl_facts\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 109, in get_facts\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 69, in populate_facts\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 600, in render_config\n  File \"/var/folders/db/lsw2l3k14ks3_ncq0k6c9vpw0000gn/T/ansible_cisco.ios.ios_acls_payload_xh9u6csw/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 208, in populate_port_protocol\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by joefodor** [comment] 2020-10-05 20:04
For me this works when I have smaller ACLs I am running IOSXE 16.12.03. when I run this on a device that has large acls I get the error from bug 155 that I posted.

**Comment by justjais** [comment] 2021-01-06 10:46
@joefodor PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:50
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:50 UTC
