### ISSUE TITLE
ios_acls  log and log_input are ignored or give wrong output

### ISSUE THREAD

**Issue by gejames** [ansible-collections/cisco.ios#190] opened 2020-10-27 14:42 UTC
##### SUMMARY
ios_acls  log and log_input are ignored or give wrong output

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_acls  log: and log_input

##### ANSIBLE VERSION

```
ansible --version
ansible 2.9.14
  config file = /home/student1/.ansible.cfg
  configured module search path = ['/home/student1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student1/.ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student1/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student1/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student1/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/.ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/home/student1/.ansible.cfg) = 200
RETRY_FILES_ENABLED(/home/student1/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ansible host:  Red Hat Enterprise Linux release 8.2 (Ootpa)

router:  Cisco IOS XE Software, Version 16.09.02

##### STEPS TO REPRODUCE

The docs say log: and log_input requrie a string but there is no option for log or log_input in ios.   If you don't add a strong to log:  it is ignored.  If you add a string, it is added to the command line and will produce an error in ios.

```
# permit tcp 10.0.0.0 0.255.255.255 any eq 22 log
              - grant: permit
                protocol: tcp
                log:
                source:
                  address: 10.0.0.0
                  wildcard_bits: 0.255.255.255
                destination:
                  any: true
                  port_protocol:
                    eq: 22
              # deny   ip any any log-input
              - grant: deny
                log_input:
                protocol: ip
                source:
                  any: true
                destination:
                  any: true
```

```
rtr1(config-ext-nacl)#permit ip any any log-input ?
  <cr>  <cr>

```

##### EXPECTED RESULTS
  log and log_input should be added to the ios acl command

like this:  
```
deny ip any any log-input
```

##### ACTUAL RESULTS
log and log-input are not added to acl commands

```
TASK [Make sure VTY ACL is correct] ****************************************************************************************************************************************************
change.
changed: [rtr1] => changed=true
  after:
  - acls:
    - aces:
      - grant: permit
        sequence: 10
        source:
          address: 192.168.35.0
          wildcard_bits: 0.0.0.255
      acl_type: standard
      name: GS_NAT_ACL
    afi: ipv4
  before:
  - acls:
    - aces:
      - grant: permit
        sequence: 10
        source:
          address: 192.168.35.0
          wildcard_bits: 0.0.0.255
      acl_type: standard
      name: GS_NAT_ACL
    afi: ipv4
  commands:
  - ip access-list extended VTY-ACL
  - permit tcp host 3.238.68.101 any eq 22
  - permit tcp 172.16.0.0 0.15.255.255 any eq 22
  - permit tcp 192.168.0.0 0.0.255.255 any eq 22
  - permit tcp 10.0.0.0 0.255.255.255 any eq 22
  - deny ip any any
```

If a string is added
```
   
              # deny   ip any any log-input
              - grant: deny
                log_input: true
                protocol: ip
                source:
                  any: true
                destination:
                  any: true
```

The output is this.     
```
commands:
  - ip access-list extended VTY-ACL
  - permit tcp host 3.238.68.101 any eq 22
  - permit tcp 172.16.0.0 0.15.255.255 any eq 22
  - permit tcp 192.168.0.0 0.0.255.255 any eq 22
  - permit tcp 10.0.0.0 0.255.255.255 any eq 22
  - deny ip any any log-input True

```

 - deny ip any any log-input True     will fail in ios

**Comment by justjais** [comment] 2021-01-06 10:45
@gejames PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:50
Closing the bug as PR #211 is merged and queued for release.

**Comment by justjais** [comment] 2021-02-11 19:17
@gejames the PR doesn't  fixes the encountered issue, so reopening the respective issue.

**Comment by justjais** [comment] 2021-03-03 17:20
@gejames I've raised the PR to address the issue you're facing currently, if feasible can you plz check the PR fix and update if that works for you as expected, and once merged it'll be queued for March'21 release.

**Closed** 2021-03-05 07:39 UTC
