### ISSUE TITLE
Expected output of ios_bgp_address_family prefix_list & route_map parameters

### ISSUE THREAD

**Issue by fakrul** [ansible-collections/cisco.ios#267] opened 2021-03-04 00:26 UTC
##### SUMMARY

Can not create both incoming and outgoing route_map & prefix_list for a bgp neighbor. It either create in filter or out filter but not both.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: ios_bgp_address_family
parameters:  prefix_list & route_map

##### ANSIBLE VERSION

```paste below
ansible 2.9.17
  config file = /home/linux/nac_ansible/ansible.cfg
  configured module search path = [u'/home/linux/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Feb 25 2021, 14:02:55) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
COMMAND_WARNINGS(/home/linux/nac_ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/home/linux/nac_ansible/ansible.cfg) = [u'/home/linux/nac_ansible/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/linux/nac_ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/linux/nac_ansible/ansible.cfg) = /home/linux/nac_ansible/ansible.log
DEFAULT_STDOUT_CALLBACK(/home/linux/nac_ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/linux/nac_ansible/ansible.cfg) = 5
DEPRECATION_WARNINGS(/home/linux/nac_ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/linux/nac_ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/home/linux/nac_ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04.4 LTS

##### STEPS TO REPRODUCE

Intent is to create both incoming and outgoing route_map and prefix_list filter for bgp neighbour using the following playbook:

```yaml
---
- hosts: routers-test
  gather_facts: no
  vars_files:
    - "../secrets/vault.yml"

  tasks:
  - name: Merge provided configuration with device configuration
    cisco.ios.ios_bgp_address_family:
      config:
        as_number: 65000
        address_family:
          - afi: ipv4
            safi: unicast
            bgp:
            neighbor:
              - address: 192.168.100.100
                remote_as: 65100
                route_map:
                  name: test-route-in
                  in: true
                  name: test-route-out
                  out: true
                prefix_list:
                  name: AS65100-PREFIX-IN
                  in: true
                  name: AS65100-PREFIX-OUT
                  out: true
            network:
              - address: 100.100.100.0
                mask: 255.255.255.0
      state: merged
```

But only creating in filter and also using wrong filter name:

```
router-test(config)#do show run | s bgp
router bgp 65000
 bgp log-neighbor-changes
 neighbor 192.168.100.100 remote-as 65100
 !
 address-family ipv4
  network 100.100.100.0 mask 255.255.255.0
  neighbor 192.168.100.100 activate
  neighbor 192.168.100.100 prefix-list AS65100-PREFIX-OUT in
  neighbor 192.168.100.100 route-map test-route-out in
```

##### EXPECTED RESULTS

Should create the following configuration:

```
router bgp 65000
 bgp log-neighbor-changes
 neighbor 192.168.100.100 remote-as 65100
 !
 address-family ipv4
  network 100.100.100.0 mask 255.255.255.0
  neighbor 192.168.100.100 activate
  neighbor 192.168.100.100 prefix-list AS65100-PREFIX-OUT out
  neighbor 192.168.100.100 prefix-list AS65100-PREFIX-IN in
  neighbor 192.168.100.100 route-map test-route-out out
 neighbor 192.168.100.100 route-map test-route-in in
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook temp_scripts/bgp_test_addrfamily.yml --vault-password-file secrets/vault_password.yml  -vvvv
ansible-playbook 2.9.17
  config file = /home/linux/nac_ansible/ansible.cfg
  configured module search path = [u'/home/linux/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Feb 25 2021, 14:02:55) [GCC 7.5.0]
Using /home/linux/nac_ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/linux/nac_ansible/hosts as it did not pass its verify_file() method
script declined parsing /home/linux/nac_ansible/hosts as it did not pass its verify_file() method
auto declined parsing /home/linux/nac_ansible/hosts as it did not pass its verify_file() method
Not replacing invalid character(s) "set([u'-'])" in group name (routers-test)
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "set([u'-'])" in group name (routers-test)
Not replacing invalid character(s) "set([u'-'])" in group name (routers-test)
Parsed /home/linux/nac_ansible/hosts inventory source with ini plugin
[WARNING]: While constructing a mapping from /home/linux/nac_ansible/temp_scripts/bgp_test_addrfamily.yml, line 20, column 19, found a duplicate dict
key (name). Using last defined value only.
[WARNING]: While constructing a mapping from /home/linux/nac_ansible/temp_scripts/bgp_test_addrfamily.yml, line 25, column 19, found a duplicate dict
key (name). Using last defined value only.
Loading callback plugin yaml of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/yaml.pyc
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: bgp_test_addrfamily.yml ***********************************************************************************************************************
Positional arguments: temp_scripts/bgp_test_addrfamily.yml
become_method: sudo
inventory: (u'/home/linux/nac_ansible/hosts',)
vault_password_files: (u'/home/linux/nac_ansible/secrets/vault_password.yml',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 5
1 plays in temp_scripts/bgp_test_addrfamily.yml
Read vars_file '../secrets/vault.yml'
Read vars_file '../secrets/vault.yml'
Read vars_file '../secrets/vault.yml'

PLAY [routers-test] *************************************************************************************************************************************
META: ran handlers
Read vars_file '../secrets/vault.yml'

TASK [Merge provided configuration with device configuration] *******************************************************************************************
task path: /home/linux/nac_ansible/temp_scripts/bgp_test_addrfamily.yml:8
Trying secret FileVaultSecret(filename='/home/linux/nac_ansible/secrets/vault_password.yml') for vault_id=default
<100.100.250.250> attempting to start connection
<100.100.250.250> using connection plugin network_cli
Trying secret FileVaultSecret(filename='/home/linux/nac_ansible/secrets/vault_password.yml') for vault_id=default
<100.100.250.250> local domain socket does not exist, starting it
<100.100.250.250> control socket path is /home/linux/.ansible/pc/ded4782abf
<100.100.250.250> local domain socket listeners started successfully
<100.100.250.250> loaded cliconf plugin ios from path /usr/lib/python2.7/dist-packages/ansible/plugins/cliconf/ios.py for network_os ios
<100.100.250.250>
<100.100.250.250> local domain socket path is /home/linux/.ansible/pc/ded4782abf
<100.100.250.250> Using network group action cisco.ios.ios for cisco.ios.ios_bgp_address_family
<100.100.250.250> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<100.100.250.250> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<100.100.250.250> ANSIBLE_NETWORK_IMPORT_MODULES: disabled for when not Python 3
<100.100.250.250> ESTABLISH LOCAL CONNECTION FOR USER: linux
<100.100.250.250> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/linux/.ansible/tmp/ansible-local-4877d5lvLl `"&& mkdir "` echo /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/ansible-tmp-1614817469.16-4884-146389683213330 `" && echo ansible-tmp-1614817469.16-4884-146389683213330="` echo /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/ansible-tmp-1614817469.16-4884-146389683213330 `" ) && sleep 0'
Using module file /home/linux/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_bgp_address_family.py
<100.100.250.250> PUT /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/tmp1FtTkq TO /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/ansible-tmp-1614817469.16-4884-146389683213330/AnsiballZ_ios_bgp_address_family.py
<100.100.250.250> EXEC /bin/sh -c 'chmod u+x /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/ansible-tmp-1614817469.16-4884-146389683213330/ /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/ansible-tmp-1614817469.16-4884-146389683213330/AnsiballZ_ios_bgp_address_family.py && sleep 0'
<100.100.250.250> EXEC /bin/sh -c 'python3 /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/ansible-tmp-1614817469.16-4884-146389683213330/AnsiballZ_ios_bgp_address_family.py && sleep 0'
<100.100.250.250> EXEC /bin/sh -c 'rm -f -r /home/linux/.ansible/tmp/ansible-local-4877d5lvLl/ansible-tmp-1614817469.16-4884-146389683213330/ > /dev/null 2>&1 && sleep 0'
[WARNING]: The value 65000 (type int) in a string field was converted to '65000' (type string). If this does not look like what you expect, quote the
entire value to ensure it does not change.
changed: [router-test] => changed=true
  after:
    address_family:
    - afi: ipv4
      neighbor:
      - activate: true
        address: 192.168.100.100
        prefix_list:
          in: true
          name: AS65100-PREFIX-OUT
        route_map:
          in: true
          name: test-route-out
      network:
      - address: 100.100.100.0
        mask: 255.255.255.0
    as_number: '65000'
  before: {}
  commands:
  - router bgp 65000
  - address-family ipv4 unicast
  - neighbor 192.168.100.100 remote-as 65100
  - neighbor 192.168.100.100 prefix-list AS65100-PREFIX-OUT in
  - neighbor 192.168.100.100 route-map test-route-out in
  - network 100.100.100.0 mask 255.255.255.0
  invocation:
    module_args:
      config:
        address_family:
        - afi: ipv4
          aggregate_address: null
          auto_summary: null
          bgp: null
          default: null
          default_information: null
          default_metric: null
          distance: null
          neighbor:
          - activate: null
            additional_paths: null
            address: 192.168.100.100
            advertise: null
            advertise_map: null
            advertisement_interval: null
            aigp: null
            allow_policy: null
            allowas_in: null
            as_override: null
            bmp_activate: null
            capability: null
            cluster_id: null
            default_originate: null
            description: null
            disable_connected_check: null
            distribute_list: null
            dmzlink_bw: null
            ebgp_multihop: null
            fall_over: null
            filter_list: null
            ha_mode: null
            inherit: null
            internal_vpn_client: null
            ipv6_adddress: null
            local_as: null
            log_neighbor_changes: null
            maximum_prefix: null
            next_hop_self: null
            next_hop_unchanged: null
            password: null
            path_attribute: null
            peer_group: null
            prefix_list:
              in: true
              name: AS65100-PREFIX-OUT
              out: true
            remote_as: 65100
            remove_private_as: null
            route_map:
              in: true
              name: test-route-out
              out: true
            route_reflector_client: null
            route_server_client: null
            send_community: null
            shutdown: null
            slow_peer: null
            soft_reconfiguration: null
            soo: null
            tag: null
            timers: null
            transport: null
            ttl_security: null
            unsuppress_map: null
            version: null
            weight: null
          network:
          - address: 100.100.100.0
            backdoor: null
            mask: 255.255.255.0
            route_map: null
          redistribute: null
          safi: unicast
          snmp: null
          table_map: null
          vrf: null
        as_number: '65000'
      running_config: null
      state: merged
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************
router-test                : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by justjais** [comment] 2021-06-22 11:01
@fakrul PR to fix the issue is merged and is queued for IOS June release.

**Closed by justjais** 2021-06-22 11:01 UTC
