### ISSUE TITLE
ios_vlans: Value Error: invalid literal

### ISSUE THREAD

**Issue by misch42** [ansible-collections/cisco.ios#237] opened 2021-02-01 20:24 UTC
##### SUMMARY
I want to set up VLANs on a Cisco IOS switch. I set up my ansible as described in the docs.

##### ISSUE TYPE
I get the error:
ValueError: invalid literal for int() with base 10: 'Ports'

##### COMPONENT NAME
cisco.ios.ios_vlans

##### ANSIBLE VERSION
Installed a fresh ansible with pip on ubuntu server 20.04

```
$ ansible --version
ansible 2.10.5
  config file = None
  configured module search path = ['/home/misch/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
```

##### CONFIGURATION
```
Nothing changed in the config
```

##### OS / ENVIRONMENT
ubuntu 20.04 server

##### STEPS TO REPRODUCE
run playbook below (copied from the docs)

```
    - name: VLAN
      cisco.ios.ios_vlans:
        config:
        - name: "VLAN20"
          vlan_id: "20"
          state: active
          shutdown: enabled
        state: merged
```

##### EXPECTED RESULTS
Sets the VLAN in the switch.

##### ACTUAL RESULTS
```
$ ansible-playbook -i inventory -vvv cisco_vlan.yaml 
ansible-playbook 2.10.5
  config file = None
  configured module search path = ['/home/misch/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
No config file found; using defaults
host_list declined parsing /home/misch/ansible/inventory/hosts.yaml as it did not pass its verify_file() method
script declined parsing /home/misch/ansible/inventory/hosts.yaml as it did not pass its verify_file() method
Parsed /home/misch/ansible/inventory/hosts.yaml inventory source with yaml plugin
redirecting (type: action) cisco.ios.ios_vlans to cisco.ios.ios
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: cisco_vlan.yaml ****************************************************************************************************************************************************
1 plays in cisco_vlan.yaml

PLAY [switch01] **************************************************************************************************************************************************************
META: ran handlers
redirecting (type: action) cisco.ios.ios_vlans to cisco.ios.ios

TASK [VLAN] ******************************************************************************************************************************************************************
task path: /home/misch/ansible/cisco_vlan.yaml:8
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_vlans to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_vlans to cisco.ios.ios
<192.168.88.128> ESTABLISH LOCAL CONNECTION FOR USER: misch
<192.168.88.128> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8 `"&& mkdir "` echo /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152 `" && echo ansible-tmp-1612211033.273754-4262-62780716424152="` echo /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152 `" ) && sleep 0'                                                                                                 
<switch01> Attempting python interpreter discovery
<192.168.88.128> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'                                                                                                                
<192.168.88.128> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py
<192.168.88.128> PUT /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/tmpkw0u16_m TO /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py                                                                                                                                        
<192.168.88.128> EXEC /bin/sh -c 'chmod u+x /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/ /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py && sleep 0'                                                                 
<192.168.88.128> EXEC /bin/sh -c '/usr/bin/python3 /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py && sleep 0'
<192.168.88.128> EXEC /bin/sh -c 'rm -f -r /home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py", line 102, in <module>
    _ansiballz_main()
  File "/home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 748, in <module>
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 743, in main
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 70, in execute_module
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 51, in get_vlans_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 117, in get_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 89, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 155, in render_config
ValueError: invalid literal for int() with base 10: 'Ports'
fatal: [switch01]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/misch/.ansible/tmp/ansible-local-4258a93ybwc8/ansible-tmp-1612211033.273754-4262-62780716424152/AnsiballZ_ios_vlans.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 748, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 743, in main\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 70, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 51, in get_vlans_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 117, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 89, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_4kud4l3e/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 155, in render_config\nValueError: invalid literal for int() with base 10: 'Ports'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by misch42** [comment] 2021-02-01 20:28
Seems to be related to #202

**Comment by justjais** [comment] 2021-02-03 11:12
@misch42 Thanks for logging the respective issue and yes it does seem to be a duplicate of #202, so closing the particular bug and carrying the conversation in the earlier tagged issue.

**Closed by justjais** 2021-02-03 11:12 UTC
