### ISSUE TITLE
ios_facts gather_network_resources index out of range for acl.py

### ISSUE THREAD

**Issue by hyudra** [ansible-collections/cisco.ios#130] opened 2020-09-02 14:41 UTC
##### SUMMARY
Got list index out of range

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.facts

##### ANSIBLE VERSION
ansible 2.9.4
python version = 3.6.8
cisco.ios = latest (1.0.3)

##### CONFIGURATION
traceback
"exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-25135treiy2ma/ansible-tmp-1599057167.0089226-61451236478499/AnsiballZ_ios_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-25135treiy2ma/ansible-tmp-1599057167.0089226-61451236478499/AnsiballZ_ios_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-25135treiy2ma/ansible-tmp-1599057167.0089226-61451236478499/AnsiballZ_ios_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_fjvutn4m/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py\", line 236, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_fjvutn4m/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py\", line 229, in main\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_fjvutn4m/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 110, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_fjvutn4m/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_fjvutn4m/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 69, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_fjvutn4m/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 600, in render_config\n  File \"/tmp/ansible_cisco.ios.ios_facts_payload_fjvutn4m/ansible_cisco.ios.ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/acls/acls.py\", line 208, in populate_port_protocol\nIndexError: list index out of range\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",

##### OS / ENVIRONMENT
awx containers on CentOS

##### STEPS TO REPRODUCE

---
- hosts: "{{network}}"
  strategy: linear
  gather_facts: false
  collections:
    - cisco.ios
  tasks:

      - name: Get facts
        cisco.ios.ios_facts:
          gather_subset: 
          - '!config'
          - 'all'
          gather_network_resources: 
            - l2_interfaces
            - interfaces
            - vlans
            - acls
            - lacp
            - lacp_interfaces
            - acl_interfaces
        ignore_unreachable: TRUE

**Comment by justjais** [comment] 2021-01-06 10:47
@hyudra PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:51
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:51 UTC
