### ISSUE TITLE
ios_acls module emits many duplicate commands in `state: replaced` mode

### ISSUE THREAD

**Issue by jamiecaesar** [ansible-collections/cisco.ios#198] opened 2020-11-03 20:51 UTC
##### SUMMARY
`ios_acls` module, when using the `state: replaced` option emits an excessive number of repeated commands, even when there should be no changes to the access list configuration.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_acls

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = /Users/jcaesar/Development/ios_acls_test/ansible.cfg
  configured module search path = ['/Users/jcaesar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jcaesar/Development/ios_acls_test/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/jcaesar/Development/ios_acls_test/venv/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/Users/jcaesar/Development/ios_acls_test/ansible.cfg) = ['/Users/jcaesar/Development/ios_acls_test/hosts']
INTERPRETER_PYTHON(/Users/jcaesar/Development/ios_acls_test/ansible.cfg) = venv/bin/python
INVENTORY_ENABLED(/Users/jcaesar/Development/ios_acls_test/ansible.cfg) = ['ini']
PARAMIKO_HOST_KEY_AUTO_ADD(/Users/jcaesar/Development/ios_acls_test/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Host OS: macOS 10.15.7
Network Devices tested against:
Cisco C819HWD-A-K9
```
Cisco IOS Software, C800 Software (C800-UNIVERSALK9_NPE-M), Version 15.7(3)M4a, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2019 by Cisco Systems, Inc.
Compiled Mon 25-Mar-19 08:23 by prod_rel_team

ROM: System Bootstrap, Version 15.2(2r)T, RELEASE SOFTWARE (fc1)
```
and
Cisco C1111-8PWB
```
Cisco IOS XE Software, Version 16.08.01
Cisco IOS Software [Fuji], ISR Software (ARMV8EB_LINUX_IOSD-UNIVERSALK9_IAS-M), Version 16.8.1, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2018 by Cisco Systems, Inc.
Compiled Tue 27-Mar-18 10:56 by mcpre
```

##### STEPS TO REPRODUCE

Configuration on device:
```
C819#show ip access-lists 
Standard IP access list 25
    20 permit 10.1.1.2
    30 permit 10.1.1.3
    10 permit 10.1.1.1
    40 permit 10.1.1.4
    50 permit 10.1.1.5
```

Running config (added using `ip access-list standard 25`, but IOS converts to older numbered format):
```
access-list 25 permit 10.1.1.2
access-list 25 permit 10.1.1.3
access-list 25 permit 10.1.1.1
access-list 25 permit 10.1.1.4
access-list 25 permit 10.1.1.5
```

```
---
- name: Update management ACLs on devices
  hosts: 192.168.5.132
  gather_facts: no
    
  tasks:
    - name: "IOS Management ACL Update"
      register: results
      cisco.ios.ios_acls:
        state: replaced
        config:
          - afi: ipv4
            acls:
              - name: "25"
                acl_type: standard
                aces:
                  - grant: permit
                    sequence: 10
                    source: 
                      address: 10.1.1.1
                  - grant: permit
                    sequence: 20
                    source: 
                      address: 10.1.1.2
                  - grant: permit
                    sequence: 30
                    source: 
                      address: 10.1.1.3
                  - grant: permit
                    sequence: 40
                    source: 
                      address: 10.1.1.4
                  - grant: permit
                    sequence: 50
                    source: 
                      address: 10.1.1.5
      check_mode: true

    - debug:
        var: results
```

##### EXPECTED RESULTS

Task marked as `ok` due to no changes needing to be made:
```
PLAY [Update management ACLs on devices] ****************************************************************************************************************************************************************************************

TASK [IOS Management ACL Update] ************************************************************************************************************************************************************************************************
ok: [192.168.5.132]

PLAY RECAP **********************************************************************************************************************************************************************************************************************
192.168.5.132              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS

```
PLAY [Update management ACLs on devices] ****************************************************************************************************************************************************************************************

TASK [IOS Management ACL Update] ************************************************************************************************************************************************************************************************
changed: [192.168.5.132]

TASK [debug] ********************************************************************************************************************************************************************************************************************
ok: [192.168.5.132] => {
    "results": {
        "after": [
            {
                "acls": [
                    {
                        "aces": [
                            {
                                "grant": "permit",
                                "sequence": 20,
                                "source": {
                                    "address": "10.1.1.2"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 30,
                                "source": {
                                    "address": "10.1.1.3"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 10,
                                "source": {
                                    "address": "10.1.1.1"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 40,
                                "source": {
                                    "address": "10.1.1.4"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 50,
                                "source": {
                                    "address": "10.1.1.5"
                                }
                            }
                        ],
                        "acl_type": "standard",
                        "name": "25"
                    }
                ],
                "afi": "ipv4"
            }
        ],
        "before": [
            {
                "acls": [
                    {
                        "aces": [
                            {
                                "grant": "permit",
                                "sequence": 20,
                                "source": {
                                    "address": "10.1.1.2"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 30,
                                "source": {
                                    "address": "10.1.1.3"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 10,
                                "source": {
                                    "address": "10.1.1.1"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 40,
                                "source": {
                                    "address": "10.1.1.4"
                                }
                            },
                            {
                                "grant": "permit",
                                "sequence": 50,
                                "source": {
                                    "address": "10.1.1.5"
                                }
                            }
                        ],
                        "acl_type": "standard",
                        "name": "25"
                    }
                ],
                "afi": "ipv4"
            }
        ],
        "changed": true,
        "commands": [
            "ip access-list standard 25",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "10 permit 10.1.1.1",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "10 permit 10.1.1.1",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "10 permit 10.1.1.1",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "10 permit 10.1.1.1",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "20 permit 10.1.1.2",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "20 permit 10.1.1.2",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "20 permit 10.1.1.2",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "20 permit 10.1.1.2",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "30 permit 10.1.1.3",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "30 permit 10.1.1.3",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "30 permit 10.1.1.3",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "30 permit 10.1.1.3",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "40 permit 10.1.1.4",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "40 permit 10.1.1.4",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "40 permit 10.1.1.4",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "40 permit 10.1.1.4",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "50 permit 10.1.1.5",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "50 permit 10.1.1.5",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "50 permit 10.1.1.5",
            "no 20",
            "no 30",
            "no 10",
            "no 40",
            "no 50",
            "50 permit 10.1.1.5"
        ],
        "failed": false
    }
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************
192.168.5.132              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

**Comment by justjais** [comment] 2021-01-06 10:45
@jamiecaesar PR #211 to fix the issue is under review, once merged it'd be queued for IOS collections Jan release.

**Comment by justjais** [comment] 2021-01-11 11:49
Closing the bug as PR #211 is merged and queued for release.

**Closed by justjais** 2021-01-11 11:49 UTC
