### ISSUE TITLE
IOS_Vlans Module Error in Ansible Tower (This playbook is working fine in Ansible Engine But not working in Ansible Tower)

### ISSUE THREAD

**Issue by jaiswaldj** [ansible-collections/cisco.ios#564] opened 2022-04-23 06:17 UTC
```
---
- hosts: switch
  connection: network_cli
  become_method: enable
  gather_facts: no
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_vlans:
        config:
        - name: Vlan_10
          vlan_id: 10
          state: active
          shutdown: disabled
          remote_span: true
        - name: Vlan_20
          vlan_id: 20
          mtu: 610
          state: active
          shutdown: enabled
        - name: Vlan_30
          vlan_id: 30
          state: suspend
          shutdown: enabled
        state: merged

    - name: Override device configuration of all VLANs with provided configuration
      cisco.ios.ios_vlans:
        config:
        - name: Vlan_10
          vlan_id: 10
          mtu: 1000
        state: overridden

    - name: Replaces device configuration of listed VLANs with provided configuration
      cisco.ios.ios_vlans:
        config:
        - vlan_id: 20
          name: Test_VLAN20
          mtu: 700
          shutdown: disabled
        - vlan_id: 30
          name: Test_VLAN30
          mtu: 1000
        state: replaced

    - name: Delete attributes of given VLANs
      cisco.ios.ios_vlans:
        config:
        - vlan_id: 10
        - vlan_id: 20
        state: deleted

    
    - name: Delete attributes of ALL VLANs
      cisco.ios.ios_vlans:
        state: deleted

    - name: Gather listed vlans with provided configurations
      cisco.ios.ios_vlans:
        config:
        state: gathered

    - name: Render the commands for provided  configuration
      cisco.ios.ios_vlans:
        config:
        - name: Vlan_10
          vlan_id: 10
          state: active
          shutdown: disabled
          remote_span: true
        - name: Vlan_20
          vlan_id: 20
          mtu: 610
          state: active
          shutdown: enabled
        - name: Vlan_30
          vlan_id: 30
          state: suspend
          shutdown: enabled
        state: rendered 

    

    - name: Showing VLan
      ios_command:
        commands: show vlan
      register: result


    - name: Display result to terminal window
      debug:
        var: result.stdout_lines


    


   


    



```

**Comment by jaiswaldj** [comment] 2022-04-23 06:18
Unsupported parameters for (cisco.ios.ios_vlans) module: provider Supported parameters include: config, running_config, state",
 Showing in Ansible Tower

**Comment by KB-perByte** [comment] 2022-04-25 06:49
Hey @jaiswaldj can you please try setting the play level variables in the inventory itself and confirm if works,
please consider setting -
```
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
```
Regards

**Comment by jaiswaldj** [comment] 2022-04-25 09:41
> Hey @jaiswaldj can you please try setting the play level variables in the inventory itself and confirm if works, please consider setting -
> 
> ```
> ansible_connection: ansible.netcommon.network_cli
> ansible_network_os: cisco.ios.ios
@KB-perByte  i have tried this also but not worked  i think there is cisco switch version issue As per blog they tested diffrent version of cisco switch that's why it will not working in Ansible Tower maybe

**Comment by KB-perByte** [comment] 2022-04-25 09:43
@jaiswaldj thanks for clarifying. Can you specify the issue better? Or if the issue is not regarding the one mentioned above we may close this issue.

**Closed** 2022-05-10 09:53 UTC
Labels: needs_info
